{{- $root := . -}}

{{- range $name := (ternary (list "server" "config" "cluster") (list "server" "config") .Values.cluster.enabled) }}
{{- $volume := index $root.Values.volumes $name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "ark.fullname" $root }}-{{ $name }}"
spec:
  storageClassName: {{ $volume.storageClassName }}
  volumeName: {{ include "ark.volumeName" (dict "Values" $root.Values "Chart" $root.Chart "Release" $root.Release "name" $name) }}
  volumeMode: Filesystem
  accessModes:
  - {{ $volume.accessMode }}
  resources:
    requests:
      storage: {{ $volume.capacity }}
{{- end }}
