# Server name
instance:
  name: Ark
  maxPlayers: 10
  password: ""
  adminPassword: ""

  extraServerOpts: ""

  # Name of the Map String to start the server
  map: TheIsland

  # Port that the server will listen on. The RAW port will always be 1 higher than this
  clientPort: 7777

  # Port the Steam Server API will listen on
  queryPort: 27015

deployment:
  # Can't be changed for now
  type: StatefulSet

  updateStrategy: RollingUpdate

# Exposes and external service of type LoadBalancer. This will be the external endpoint that
# players connect to
service:
  type: LoadBalancer

  # Additional annotations to add (for example to setup ALB/MetalLB)
  annotations:
  # loadBalancerIP:

# Run the server on a specific node
nodeAffinity:
  matchExpressions:
  - key: kubernetes.io/hostname
    operator: In
    values:
    - worker-1

# Should clustering be enabled? This requires ReadWriteMany volumes
cluster:
  enabled: true
  id: cluster

  # Share the server, config, and data folders
  shareVolumes: true

# Volumes for game data
volumes:
  server:
    create: true

    storageClassName: local-storage
    # Can also be ReadWriteOnce, but will result in data duplication
    accessMode: ReadWriteMany
    capacity: 30Gi
    options:
      local:
        path: "/opt/ark-data/server"
  config:
    create: true

    storageClassName: local-storage
    # Can also be ReadWriteOnce, but will result in data duplication
    accessMode: ReadWriteMany
    capacity: 100Mi
    options:
      local:
        path: "/opt/ark-data/config"
  cluster:
    create: true

    storageClassName: local-storage
    accessMode: ReadWriteMany
    capacity: 100Mi
    options:
      local:
        path: "/opt/ark-data/cluster"
  save:
    storageClassName: local-storage
    accessMode: ReadWriteOnce
    capacity: 5Gi
    options:
      local:
        path: "/opt/ark-data/save/TheIsland"
